#!/usr/bin/env python3
"""Unifies PortTorch.meta.yml + PortTorch.py into the single PortTorch.yml
that gets uploaded through the XSOAR web UI (Settings -> Integrations ->
BYOI).

XSOAR's BYOI upload takes exactly one file, with the Python embedded in
`script.script` - but a Python file living inside a YAML string cannot be
compiled, linted or diffed usefully, so the source stays its own file and
this puts the two together. Same split demisto-sdk's `unify` performs;
written out here so the build needs nothing but a stock Python.

Run after editing either source file:

    python3 build_yml.py && python3 validate.py
"""

import pathlib
import sys

import yaml

HERE = pathlib.Path(__file__).parent
META = HERE / "PortTorch.meta.yml"
SOURCE = HERE / "PortTorch.py"
UNIFIED = HERE / "PortTorch.yml"

HEADER = (
    "# Generated by build_yml.py - do not edit directly.\n"
    "# Sources: PortTorch.meta.yml (metadata) + PortTorch.py (code).\n"
    "# Upload this file in Cortex XSOAR: Settings -> Integrations -> BYOI.\n"
)


class LiteralBlock(str):
    """A string to emit as a literal block scalar, so the embedded Python
    stays readable (and reviewable) inside the unified YAML."""


def _literal_representer(dumper, data):
    return dumper.represent_scalar("tag:yaml.org,2002:str", str(data), style="|")


yaml.add_representer(LiteralBlock, _literal_representer)


def main() -> int:
    integration = yaml.safe_load(META.read_text())

    # A literal block scalar cannot carry trailing whitespace on a line -
    # PyYAML silently falls back to a quoted scalar if it finds any, which
    # still loads correctly but turns the embedded code into one
    # unreadable escaped string.
    code = "\n".join(line.rstrip() for line in SOURCE.read_text().splitlines()) + "\n"
    integration["script"]["script"] = LiteralBlock(code)

    body = yaml.dump(integration, sort_keys=False, allow_unicode=True, width=10_000, default_flow_style=False)
    UNIFIED.write_text(HEADER + body)
    print(f"wrote {UNIFIED} ({UNIFIED.stat().st_size} bytes, {len(code.splitlines())} lines of Python)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
